env:
  browser: true
  es2021: true
extends: eslint:recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  object-curly-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - always
  comma-spacing:
    - error
  space-before-function-paren:
    - error
    - never
  arrow-parens:
    - error
    - as-needed
  max-len:
    - warn
    - code: 90
      tabWidth: 2
      ignoreTemplateLiterals: true
  complexity:
    - warn
    - 8
  key-spacing:
    - error
    - afterColon: true

